server:
  port: 8787

spring:
  data:
    mongodb:
      database: mail-cms
      host: ${MONGO_DB_HOST:localhost}
      port: ${MONGO_DB_PORT:27017}
      username: ${MONGO_DB_USERNAME:username}
      password: ${MONGO_DB_PASSWORD:password}

jwt:
  secret: ${JWT_SECRET:04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1}

logging:
  level:
    com.uni.bankcmsapi: debug
